# Конфигурация для тестового задания.
# Сделала упрощенно, без .env. НО в реальном проекте пароли и секреты хранятся в переменных окружения.


server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres_db:5432/bankcards
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # временно, чтобы база сама создалась
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml

jwt:
  secret: mysecretkey123456789
  expiration: 3600000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

app:
  encryption-key: JiCg3EjENoPuI7uEDWZsZw==