server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres_db:5432/bankcards
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml

jwt:
  secret: G3i3f49Fj5P2O7s0A9t7S0y3Y4H8u1J1L2p5K9l3M8n0B5q2R7v9T4w1X6z0C4d3E5h7I8k6M
  expiration:
    ms: 3600000
  refresh:
    expiration:
      ms: 604800000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

app:
  encryption-key: G3i3f49Fj5P2O7s0A9t7S0y3Y4H8u1J1L2p5K9l3M8n0B5q2R7v9T4w1X6z0C4d3E5h7I8k6M
